require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Rakefile"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "config.ru"
    - "lib/generators/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "app/lib/simple_command.rb"
    - "app/lib/simple_command/**/*"
    - "app/controllers/rails_admin/**/*"

Layout/LineLength:
  Max: 115

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake

Metrics/MethodLength:
  Max: 12
  Exclude:
    - app/mailers/sendgrid_web_mailer.rb
    - app/queries/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/PredicateMatcher:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NoExpectationExample:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - app/blueprints/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/commands/**/*
    - app/lib/**/*
    - app/mailers/sendgrid_web_mailer.rb

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - app/controllers/api/v1/manager/**/*
    - app/controllers/api/v1/person_payments_controller.rb
    - app/lib/date_range/splitter.rb

Rails/DynamicFindBy:
  Enabled: false
