require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'Rakefile'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config.ru'
    - 'lib/generators/**/*'
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 12

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Rspec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Rspec/PredicateMatcher:
  Enabled: false

Rspec/NestedGroups:
  Max: 4

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

Style/SymbolProc:
  Exclude:
    - app/blueprints/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false