default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db
  database: ribon_core_api
  pool: 5

development: 
  <<: *default

test:
  <<: *default