default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5

development: 
  <<: *default
  database: ribon_core_api_development

test:
  <<: *default
  database: ribon_core_api_test