send_donation_batch:
  cron: "0 1 * * 1" # At 01:00 on monday.
  class: "Donations::SendDonationBatchWorker"
  queue: donations

retry_donation_batch:
  cron: "0 1 1 * *" # At 01:00 on day-of-month 1.
  class: "Donations::RetryDonationBatchWorker"
  queue: donations

generate_balance_history:
  cron: "0 2 * * *" # At 02:00 everyday.
  class: "Donations::GenerateBalanceHistoryWorker"
  queue: donations

retry_person_transactions:
  cron: "0 2 1 * *" # At 02:00 on day-of-month 1.
  class: "PersonPayments::RetryBlockchainTransactionsWorker"
  queue: person_payments
  
inactive_donors_one_week_worker:
  cron: "0 9 * * 0" # At 09:00 everyday.
  class: "Mailers::SendOneWeekInactivityEmailWorker"
  queue: mailers

inactive_donors_months_worker:
  cron: "0 10 * * 0" # At 10:00 everyday.
  class: "Mailers::SendMonthsInactivityEmailWorker"
  queue: mailers

