send_donation_batch:
  cron: "0 1 * * 1" # At 01:00 on monday.
  class: "Donations::SendDonationBatchWorker"
  queue: batches

retry_donation_batch:
  cron: "0 1 1 * *" # At 01:00 on day-of-month 1.
  class: "Donations::RetryDonationBatchWorker"
  queue: batches

update_blockchain_transactions:
  cron: "0 3 * * *" # At 03:00 everyday.
  class: "Donations::UpdateBlockchainTransactionsWorker"
  queue: donations

generate_balance_history:
  cron: "0 2 * * *" # At 02:00 everyday.
  class: "Donations::GenerateBalanceHistoryWorker"
  queue: donations

update_pool_balance:
  cron: "0 4 * * *" # At 04:00 everyday.
  class: "Donations::UpdatePoolBalanceWorker"
  queue: donations

retry_person_transactions:
  cron: "*/30 * * * *" # Every 30 minutes.
  class: "PersonPayments::RetryBlockchainTransactionsWorker"
  queue: person_payments
  
send_bimonthly_email_report_worker:
  cron: "0 18 1 * *" # At 18:00 on day-of-month 1.
  class: "Mailers::SendBimonthlyEmailReportWorker"
  queue: mailers

inactive_donors_one_week_worker:
  cron: "0 9 * * 0" # At 09:00 everyday.
  class: "Mailers::SendOneWeekInactivityEmailWorker"
  queue: mailers

inactive_donors_months_worker:
  cron: "0 10 * * 0" # At 10:00 everyday.
  class: "Mailers::SendMonthsInactivityEmailWorker"
  queue: mailers

contribution_reactivation_months_worker:
  cron: "0 11 * * *" # At 11:00 everyday.
  class: "Mailers::CheckForContributionReactivationWorker"
  queue: mailers

label_missed_donations:
  cron: "0 3 * * 1" # At 03:00 on monday.
  class: "Contributions::LabelMissedDonationsWorker"
  queue: contributions

create_contribution_for_missed_payments:
  cron: "0 2 * * 1" # At 02:00 on monday.
  class: "Contributions::CreateContributionForMissedPaymentsWorker"
  queue: contributions

run_relabel_script:
  cron: "0 8 * 3 1" # At 08:00 on Monday in March. TODO: Remove this after run
  class: "Contributions::RelabelWorker"
  queue: relabel