send_donation_batch:
  cron: "0 1 * * 1" # At 01:00 on monday.
  class: "Donations::SendDonationBatchWorker"
  queue: batches

retry_donation_batch:
  cron: "0 1 1 * *" # At 01:00 on day-of-month 1.
  class: "Donations::RetryDonationBatchWorker"
  queue: batches

update_blockchain_transactions:
  cron: "0 3 * * *" # At 03:00 everyday.
  class: "Donations::UpdateBlockchainTransactionsWorker"
  queue: donations

generate_balance_history:
  cron: "0 2 * * *" # At 02:00 everyday.
  class: "Donations::GenerateBalanceHistoryWorker"
  queue: donations

update_pool_balance:
  cron: "0 4 * * *" # At 04:00 everyday.
  class: "Donations::UpdatePoolBalanceWorker"
  queue: donations

retry_person_transactions:
  cron: "*/30 * * * *" # Every 30 minutes.
  class: "PersonPayments::RetryBlockchainTransactionsWorker"
  queue: person_payments

label_missed_donations:
  cron: "0 3 * * 1" # At 03:00 on monday.
  class: "Contributions::LabelMissedDonationsWorker"
  queue: contributions

create_contribution_for_missed_payments:
  cron: "0 2 * * 1" # At 02:00 on monday.
  class: "Contributions::CreateContributionForMissedPaymentsWorker"
  queue: contributions

clear_all_collected_by_integration:
  cron: "1 0 * * *" # At 00:01.
  class: "Tickets::ClearAllCollectedByIntegrationWorker"
  queue: tickets

clear_expired_coupons:
  cron: "0 4 * * 1" # At 04:00 on monday.
  class: "Coupons::ClearExpiredCouponsWorker"
  queue: coupons

generate_club_daily_tickets:
  cron: "0 1 * * *" # At 01:00 everyday.
  class: "Tickets::GenerateClubDailyTicketsWorker"
  queue: tickets

clear_redis_tickets:
  cron: "0 1 10 1 *" # At 01:00 on day-of-month 10 in January.
  class: "Tickets::ClearRedisTicketsWorker"
  queue: tickets

label_donations_and_contributions:
  cron: "0 8 * 3 1"
  class: "Contributions::LabelWorker"
  queue: relabel

relabel_donations_and_contributions:
  cron: "0 8 * 3 1"
  class: "Contributions::RelabelWorker"
  queue: relabel

clear_old_integration_tickets:
  cron: "0 1 20 1 *" # At 01:00 January 20th
  class: "Tickets::ClearOldIntegrationTicketsWorker"
  queue: tickets

reset_donation_streak:
  cron: "0 3 * * *" # At 03:00 everyday.
  class: "Users::ResetDonationStreakWorker"
  queue: users

reset_everyone_donation_streak:
  cron: "0 1 * * *" # At 01:00 everyday.
  class: "Users::ResetEveryoneDonationStreakWorker"
  queue: users
