name: After Test Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Tests (6)'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Test
        run: echo test after test