name: Tests
on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 6 ]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run setup database test
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test_setup
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          MUMBAI_NODE_URL: ${{ secrets.MUMBAI_NODE_URL }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          MUMBAI_BLOCK_EXPLORER_URL: ${{ secrets.MUMBAI_BLOCK_EXPLORER_URL }}
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:drop
          bundle exec rails db:setup
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - name: Run Linter
        run: bundle exec rubocop
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          COVERAGE: true
          MIN_COVERAGE: 93
          RIBON_WALLET_PRIVATE_KEY: ${{ secrets.RIBON_WALLET_PRIVATE_KEY }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          BLOCKCHAIN_SCAN_URL: ${{ secrets.BLOCKCHAIN_SCAN_URL }}
          THE_GRAPH_URL: ${{ secrets.THE_GRAPH_URL }}
          CURRENCY_API_URL: ${{ secrets.CURRENCY_API_URL }}
          POLYGON_GAS_FEE_URL: ${{ secrets.POLYGON_GAS_FEE_URL }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}
          SENTRY_DSN_URL: ${{ secrets.SENTRY_DSN_URL }}
          MUMBAI_NODE_URL: ${{ secrets.MUMBAI_NODE_URL }}
          MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
          MUMBAI_BLOCK_EXPLORER_URL: ${{ secrets.MUMBAI_BLOCK_EXPLORER_URL }}
          RIBON_SECRET_OPENSSL_KEY: ${{ secrets.RIBON_SECRET_OPENSSL_KEY }}
          INTEGRATION_ADDRESS_BASE_URL: ${{ secrets.INTEGRATION_ADDRESS_BASE_URL }}
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec