name: Merge on develop
on:
  pull_request:
    branches:
    - staging
jobs:
  updateTestFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Tests (6)'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 15
      - name: Merge PR branch -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.event.pull_request.head.ref }}
          target_branch: develop
          github_token: "${{ secrets.GITHUB_TOKEN }}"