name: Merge on fix/test-flow
on:
  pull_request:
    branches:
    - staging
jobs:
  updateTestFlow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge PR branch -> fix/test-flow
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.event.pull_request.head.ref }}
          target_branch: fix/test-flow
          github_token: "${{ secrets.GITHUB_TOKEN }}"
